name: workflows

on:
  schedule:
    - cron: '0 11 * * *' # Run nightly at 11am UTC (3am Pacific, 6am Eastern)
  pull_request:
    paths:
      - '**'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  pytype:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install absl-py paramaterized pytype
      - run: pytype *.py

  unittest:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install absl-py paramaterized
      - run: python -m unittest -v *_test.py

  pyflakes:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install absl-py paramaterized pyflakes
      - run: pyflakes *.py

  pyink:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install absl-py paramaterized pyink
      - run: ./format.sh --diff --no-color
